; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:pico]
platform = https://github.com/maxgerhardt/platform-raspberrypi.git
board = pico
framework = arduino
board_build.core = earlephilhower

; Monitor settings
monitor_speed = 115200

; Build flags
build_flags = 
    -D USE_TINYUSB 
    -D USE_TINYUSB_HOST
    ; -D CFG_TUSB_DEBUG=2
    ; -D CFG_TUH_LOG_LEVEL=2
    ; -D SIMULATE

; If you need to use the PIO assembler (pioasm) automatically, 
; the Earle Philhower core usually handles .pio files in src/ 
; or you might need to generate headers manually if using advanced features.
