// -------------------------------------------------- //
// This file is autogenerated by pioasm; do not edit! //
// -------------------------------------------------- //

#pragma once

#if !PICO_NO_HARDWARE
#include "hardware/pio.h"
#endif

// --- //
// bus //
// --- //

#define bus_wrap_target 0
#define bus_wrap 18
#define bus_pio_version 0

static const uint16_t bus_program_instructions[] = {
            //     .wrap_target
    0x202a, //  0: wait   0 pin, 10
    0x4008, //  1: in     pins, 8
    0x00cf, //  2: jmp    pin, 15
    0x4069, //  3: in     null, 9
    0xe081, //  4: set    pindirs, 1
    0xe000, //  5: set    pins, 0
    0x80a0, //  6: pull   block
    0xa007, //  7: mov    pins, osr
    0xa0e2, //  8: mov    osr, y
    0x6088, //  9: out    pindirs, 8
    0xe080, // 10: set    pindirs, 0
    0x20a8, // 11: wait   1 pin, 8
    0xa0e3, // 12: mov    osr, null
    0x6088, // 13: out    pindirs, 8
    0x0012, // 14: jmp    18
    0x2029, // 15: wait   0 pin, 9
    0x4008, // 16: in     pins, 8
    0x4041, // 17: in     y, 1
    0x20aa, // 18: wait   1 pin, 10
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program bus_program = {
    .instructions = bus_program_instructions,
    .length = 19,
    .origin = -1,
    .pio_version = bus_pio_version,
#if PICO_PIO_VERSION > 0
    .used_gpio_ranges = 0x0
#endif
};

static inline pio_sm_config bus_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + bus_wrap_target, offset + bus_wrap);
    return c;
}

static inline void bus_program_init(PIO pio, uint sm, uint offset, uint base_pin) {
    pio_sm_config c = bus_program_get_default_config(offset);
    // 1. Configure Pin Mappings
    sm_config_set_in_pins(&c, base_pin);
    sm_config_set_out_pins(&c, base_pin, 8);
    sm_config_set_set_pins(&c, base_pin + 11, 1);
    sm_config_set_jmp_pin(&c, base_pin + 8);
    // 2. Configure Shift Directions
    // IN Shift: Left, Autopush ON
    // ISR = (ISR << count) | Input.
    // We shift in: Address(8) -> Data/Dummy(8) -> Flag(1).
    sm_config_set_in_shift(&c, false, true, 17); 
    // OUT Shift: Right, Autopull OFF
    sm_config_set_out_shift(&c, true, false, 32);
    // 3. Initialize GPIOs
    for (uint i = 0; i <= 11; i++) {
        pio_gpio_init(pio, base_pin + i);
    }
    // 4. Set Pin Directions (All Input initially)
    pio_sm_set_consecutive_pindirs(pio, sm, base_pin, 12, false);
    // 5. Pre-load Y register with 0xFFFFFFFF
    pio_sm_exec(pio, sm, pio_encode_mov_not(pio_y, pio_null));
    // 6. Init and Enable
    pio_sm_init(pio, sm, offset, &c);
    pio_sm_set_enabled(pio, sm, true);
}

#endif

